[package]
name = "cartesien_tree"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand ={ version = "2", optional = true}

[profile.release]
strip = true
panic = "abort"
lto = true
codegen-units = 1

[features]
benchmark = ["dep:fastrand"]